/*
-- Query: SELECT * FROM Journeyman.HockeyGame
LIMIT 0, 1000

-- Date: 2021-09-05 00:23
*/
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('EJEPL',1,'League',0,'0','0',3,'AA',1,'Nassau',0,20,NULL,NULL,1,3,'Home',6,1,3);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('EJEPL',2,'League',0,'0','0',3,'AA',1,'Darien',0,20,NULL,NULL,1,1,'Away',10,2,3);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('EJEPL',1,'League',1,'0','0',3,'AA',1,'Central Caps',0,20,NULL,NULL,1,3,'Home',7,3,3);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('EJEPL',0,'League',1,'0','0',3,'AA',0,'CT Riverhawks',0,20,NULL,NULL,1,3,'Home',2,4,3);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('Exhibition',0,'NonLeague',0,'0','0',3,'AA',0,'Loudoun Knights Gold',0,20,NULL,NULL,NULL,0,'Away',0,5,3);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('Exhibition',0,'NonLeague',0,'0','0',3,'AA',0,'Loudoun Knights Gold',0,20,NULL,NULL,NULL,0,'Home',0,6,3);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('2021 Ice Works Summer Fire Tournament',0,'Tournament',0,'0','0',3,'AA',2,'Aston Thunder Cats',0,13,NULL,NULL,1,1,'Home',5,7,4);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('2021 Ice Works Summer Fire Tournament',0,'Tournament',0,'0','0',3,'AA',13,'Gotta Hockey',0,13,NULL,NULL,2,0,'Home',0,8,4);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('2021 Ice Works Summer Fire Tournament',0,'Tournament',0,'0','0',3,'AA',3,'Delco Phantoms',0,13,NULL,NULL,2,0,'Home',2,9,4);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('2021 Ice Works Summer Fire Tournament',0,'Tournament',0,'1','0',3,'AA',14,'Gotta Hockey',0,13,NULL,NULL,2,4,'Home',0,10,4);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('2021 One Hockey Philadelphia Summer',0,'Tournament',0,'0','0',3,'AAA',4,'Aston 1494',0,15,NULL,NULL,1,2,'Away',9,11,4);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('2021 One Hockey Philadelphia Summer',1,'Tournament',0,'0','0',3,'AAA',2,'Hockey Lab',0,15,NULL,NULL,1,2,'Away',7,12,4);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('2021 One Hockey Philadelphia Summer',1,'Tournament',0,'0','0',3,'AAA',2,'Valley Forge Minutemen',0,15,'Played wing',NULL,1,5,'Home',7,13,4);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('2021 One Hockey Philadelphia Summer',1,'Tournament',0,'1','0',3,'AAA',7,'Hockey Lab',0,15,NULL,'Championship game.',4,4,'Home',6,14,4);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('Bowie Mini-Jamboree',0,'NonLeague',0,'0','0',3,'LA',0,'STJ',0,20,NULL,NULL,NULL,0,'Away',0,15,5);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('Bowie Mini-Jamboree',0,'NonLeague',0,'0','0',3,'LA',0,'Southern Maryland',0,20,NULL,NULL,NULL,0,'Away',0,16,5);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('Bowie Mini-Jamboree',0,'NonLeague',0,'0','0',3,'LA',0,'Bowie',0,20,NULL,NULL,NULL,0,'Away',0,17,5);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('CBHL',0,'NonLeague',0,'0','0',3,'LA',0,'Frederick',0,20,NULL,NULL,NULL,0,'Away',0,18,5);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('Exhibition',2,'NonLeague',1,'1','0',3,'LA',3,'Loudon Knights',0,20,NULL,NULL,1,3,'Home',7,19,1);
INSERT INTO `` (`League`,`Assists`,`GameType`,`Goals`,`IsOvertime`,`IsPlayoff`,`NumPeriods`,`OpponentLevel`,`OpponentScore`,`OpponentTeamName`,`PenaltyMin`,`PeriodLength`,`PostGameNotes`,`PreGameNotes`,`Result`,`Shots`,`Side`,`TeamScore`,`EventId`,`TeamId`) VALUES ('CBHL',1,'League',0,'0','0',3,'UA',4,'Howard Huskies',0,20,NULL,NULL,1,5,'Away',5,20,1);
